name: Frontend Node.JS CI/CD

on:
  push:
    branches: [ main ]

jobs:
       
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
     - name: Deploy to production
       uses: johnbeynon/render-deploy-action@v0.0.8
       with:
        serviceid: ${{ secrets.SERVICE_ID }}  
        api-key: ${{ secrets.RENDER_API_KEY }}  
